version: '2'#make sure you build first
services:
  web:
    build: ./currency-quiz
    expose:
      - "5000"
    environment:
      - VIRTUAL_HOST=currency-quiz.maonoi.com
      - LETSENCRYPT_HOST=currency-quiz.maonoi.com
      - LETSENCRYPT_EMAIL=piti118@gmail.com
    network_mode: "bridge"
