#make sure you build first
build:
  image: node:7
  volumes:
    - ./static:/usr/share/nginx/html:ro
  expose:
    - "80"
  environment:
    - VIRTUAL_HOST=python.maonoi.com
    - LETSENCRYPT_HOST=python.maonoi.com
    - LETSENCRYPT_EMAIL=piti118@gmail.com
